name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

        - name: macOS
          os: macos-latest

        - name: Android32
          os: ubuntu-latest
          target: Android32

        - name: Android64
          os: ubuntu-latest
          target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          combine: true
          target: ${{ matrix.config.target }}
  build-2:
    name: Build 2
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Download Node IDs
        run: |
          mkdir -p build/geode-deps/geode.node-ids/
          curl -L -o ./geode.node-ids.geode https://github.com/Kingminer7/NodeIDs/releases/download/1.13.2/geode.node-ids.geode
          7z x './geode.node-ids.geode' '-o./build/geode-deps/geode.node-ids'
          echo '{ "required": true }' > build/geode-deps/geode.node-ids/geode-dep-options.json

      - name: Build 2
        uses: geode-catgirls/build-geode-mod@main
        with:
          bindings: geode-catgirls/bindings
          target: iOS
          gh-pat: ${{ secrets.GH_PAT }}
          # super secret
      - run: |
            find . -type f
            find ./output -type f
          
  package:
    name: Package and release mod
    runs-on: ubuntu-latest
    needs: ['build', 'build-2']
    steps:
      - uses: geode-catgirls/build-geode-mod/combine@main
        id: build
        name: Combine mods

      - uses: actions/upload-artifact@v4
        name: Upload artifact
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
